---
# Source: argopoc/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "assignment-test-connection"
  labels:
    app.kubernetes.io/instance: "assignment"
    app.kubernetes.io/name: "test-connection"
spec:
  containers:
    - name: "assignment-curl"
      image: curlimages/curl:7.71.1
      command: ['curl']
      args: ["http://assignment:80"]
apiVersion: v1
kind: Pod
metadata:
  name: "assignmentstatus-test-connection"
  labels:
    app.kubernetes.io/instance: "assignmentstatus"
    app.kubernetes.io/name: "test-connection"
spec:
  containers:
    - name: "assignmentstatus-curl"
      image: curlimages/curl:7.71.1
      command: ['curl']
      args: ["http://assignmentstatus:80"]
apiVersion: v1
kind: Pod
metadata:
  name: "bulktag-test-connection"
  labels:
    app.kubernetes.io/instance: "bulktag"
    app.kubernetes.io/name: "test-connection"
spec:
  containers:
    - name: "bulktag-curl"
      image: curlimages/curl:7.71.1
      command: ['curl']
      args: ["http://bulktag:80"]
apiVersion: v1
kind: Pod
metadata:
  name: "documentloader-test-connection"
  labels:
    app.kubernetes.io/instance: "documentloader"
    app.kubernetes.io/name: "test-connection"
spec:
  containers:
    - name: "documentloader-curl"
      image: curlimages/curl:7.71.1
      command: ['curl']
      args: ["http://documentloader:80"]
apiVersion: v1
kind: Pod
metadata:
  name: "export-test-connection"
  labels:
    app.kubernetes.io/instance: "export"
    app.kubernetes.io/name: "test-connection"
spec:
  containers:
    - name: "export-curl"
      image: curlimages/curl:7.71.1
      command: ['curl']
      args: ["http://export:80"]
---
# Source: argopoc/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment
  template:
    metadata:
      labels:
        app: assignment
    spec:
      containers:
      - name: assignment
        image: redon/assignment:2024.7.1
        ports:
        - containerPort: 80
---
# Source: argopoc/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignmentstatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignmentstatus
  template:
    metadata:
      labels:
        app: assignmentstatus
    spec:
      containers:
      - name: assignmentstatus
        image: redon/assignmentstatus:2024.7.31
        ports:
        - containerPort: 80
---
# Source: argopoc/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulktag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulktag
  template:
    metadata:
      labels:
        app: bulktag
    spec:
      containers:
      - name: bulktag
        image: redon/bulktag:2024.7.31
        ports:
        - containerPort: 80
---
# Source: argopoc/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documentloader
  template:
    metadata:
      labels:
        app: documentloader
    spec:
      containers:
      - name: documentloader
        image: redon/documentloader:2024.7.31
        ports:
        - containerPort: 80
---
# Source: argopoc/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: export
spec:
  replicas: 1
  selector:
    matchLabels:
      app: export
  template:
    metadata:
      labels:
        app: export
    spec:
      containers:
      - name: export
        image: redon/export:2024.7.31
        ports:
        - containerPort: 80
