---
# Source: argopoc/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment
  template:
    metadata:
      labels:
        app: assignment
    spec:
      containers:
      - name: assignment
        image: redon/assignment:2024.7.1
        ports:
        - containerPort: 80
---
# Source: argopoc/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignmentstatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignmentstatus
  template:
    metadata:
      labels:
        app: assignmentstatus
    spec:
      containers:
      - name: assignmentstatus
        image: redon/assignmentstatus:2024.7.46
        ports:
        - containerPort: 80
---
# Source: argopoc/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulktag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulktag
  template:
    metadata:
      labels:
        app: bulktag
    spec:
      containers:
      - name: bulktag
        image: redon/bulktag:2024.7.46
        ports:
        - containerPort: 80
---
# Source: argopoc/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documentloader
  template:
    metadata:
      labels:
        app: documentloader
    spec:
      containers:
      - name: documentloader
        image: redon/documentloader:2024.7.46
        ports:
        - containerPort: 80
---
# Source: argopoc/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: export
spec:
  replicas: 1
  selector:
    matchLabels:
      app: export
  template:
    metadata:
      labels:
        app: export
    spec:
      containers:
      - name: export
        image: redon/export:2024.7.46
        ports:
        - containerPort: 80
