{{- $externalValues := mergeOverwrite .Values.external .Values }}
{{- range $key, $value := .Values.review.review_services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $value.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $value.name }}
  template:
    metadata:
      labels:
        app: {{ $value.name }}
    spec:
      containers:
      - name: {{ $value.name }}
        {{- $service := index $externalValues.services $key | default dict }}
        {{- $serviceTag := $service.tag | default "" }}
        {{- $versionTag := index $externalValues.versions (printf "default_%s" "review") | default "" }}
        {{- $tag := $serviceTag | default $versionTag | default $value.tag }}
        image: {{ $value.image }}:{{ $tag }}
        ports:
        - containerPort: {{ $value.containerPort | default 80 }}
{{- end }}