configMap:
  config_values:
    defaultAgentVersion: 11.0.0.0
    defaultManagerVersion: 10.1.2024.1
    msaVersionOverrides:
      '92510001': 2024.3.0.525
      '92512064': 2024.3.0.521
image:
  pullPolicy: IfNotPresent
  repository: redon/agent-watcher
  tag: latest
replicaCount: 1
