configMap:
  config_values:
    default_agent_version: 11.0.0.0
    default_manager_version: 10.1.2024.1
    msa_version_overrides:
      '81010001': 11.0.0.1
      '81010002': 12.0.0.1
      '81010003': 11.1.2.5
image:
  pullPolicy: IfNotPresent
  repository: redon/agent-watcher
  tag: latest
replicaCount: 1
