configMap:
  config_values:
    defaultAgentVersion: 11.0.0.0
    defaultManagerVersion: 10.1.2024.1
    msaVersionOverrides:
      '81010001': 11.0.1.3
      '81010002': 12.0.0.2
      '81010003': 11.1.2.5
      '92510001': 2024.3.0.525
      '92512064': 2024.3.0.521
image:
  pullPolicy: IfNotPresent
  repository: redon/agent-watcher
  tag: latest
replicaCount: 1
